version: '3'
services:
  solr:
    build: .        
    container_name: Solr662
    hostname: localhost
    ports:
      - '8983:8983'
    environment: 
      - SOLR_HOME=/solr662
      - INIT_SOLR_HOME=yes
    volumes:
      - '../SolrData/Server/Solr:/solr662'
